<?php
/**
 * Created by PhpStorm.
 * User: ikorostelev
 * Date: 26.06.18
 * Time: 10:14
 */

namespace common\widgets;

use Yii;
use yii\base\Widget;
use yii\helpers\Html;


class TreeView extends Widget
{
    public $dataProvider;
    public $message;
    /**
     * @var string the caption of the grid table
     * @see captionOptions
     */
    public $caption;
    /**
     * @var array the HTML attributes for the grid table element.
     * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
     */
    public $tableOptions = ['class' => 'table table-striped table-bordered'];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if ($this->dataProvider){
            echo "<ol>";
            foreach($this->dataProvider->getModels() as $model){
                echo "<li>{$model->name}</li>";
                echo "<ol>";
                if ($model->getChildTree()){
                    foreach ($model->getChildTree() as $child){
                        echo "<li>{$child->name} ({$child->id})</li>";
                        echo "<ol>";
                        if ($child->getChildTree()){
                            foreach ($child->getChildTree() as $item){
                                echo "<li>{$item->name} ({$item->id})</li>";
                            }
                        }
                        echo "</ol>";
                    }
                }
                echo "</ol>";
            }
            echo "</ol>";
        }else{
            echo Html::encode('записей нет');
        }
    }

}